# Generated by Django 4.1.3 on 2022-12-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptouser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cryptouser',
            name='user_permissions',
        ),
    ]
