# Generated by Django 4.1.3 on 2022-12-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cryptouser_groups_cryptouser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptouser',
            options={'verbose_name': 'User'},
        ),
    ]
