# Generated by Django 4.1.3 on 2022-11-30 03:47

import Crypto_web.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True, validators=[Crypto_web.common.validators.validate_alphabet_characters_english])),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
