# Generated by Django 4.1.3 on 2022-12-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helparticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helparticle',
            options={'verbose_name': 'Help Article'},
        ),
    ]
