# Generated by Django 4.1.3 on 2022-11-11 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Etherium', 'Etherium'), ('Cardano', 'Cardano'), ('BNB', 'BNB'), ('USDT', 'USDT')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
