# Generated by Django 4.1.3 on 2022-11-13 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_coin_stable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='stable',
        ),
        migrations.AddField(
            model_name='coin',
            name='quantity',
            field=models.FloatField(default=1, max_length=10000000, validators=[django.core.validators.MinValueValidator(1e-08), django.core.validators.MaxValueValidator(10000)]),
            preserve_default=False,
        ),
    ]
