# Generated by Django 4.1.3 on 2022-11-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_helparticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helparticle',
            name='author',
        ),
    ]
