# Generated by Django 4.1.3 on 2022-11-14 16:14

import Crypto_web.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_contactus_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile_number',
            field=models.CharField(max_length=13, validators=[Crypto_web.web.validators.validate_if_number_starts_with_country_code, django.core.validators.MinLengthValidator(10, message='The number is incorrect.')]),
        ),
    ]
