# Generated by Django 4.1.3 on 2022-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_contactus_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'NewsLetter',
            },
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='newsletter',
        ),
    ]
