# Generated by Django 4.1.3 on 2022-11-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_contactus_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='newsletter',
        ),
    ]
