# Generated by Django 4.1.3 on 2022-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_coin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Etherium', 'Etherium'), ('Cardano', 'Cardano'), ('BNB', 'BNB'), ('USDT', 'USDT')], max_length=8),
        ),
    ]
