# Generated by Django 4.1.3 on 2022-11-22 04:12

import Crypto_web.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_coin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile_number',
            field=models.CharField(max_length=13, validators=[Crypto_web.common.validators.validate_if_number_starts_with_country_code, django.core.validators.MinLengthValidator(10, message='The number is incorrect.')]),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[Crypto_web.common.validators.validate_alphabet_characters_english]),
        ),
    ]
