# Generated by Django 4.1.3 on 2022-11-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_coin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='wallet_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
