# Generated by Django 4.1.3 on 2022-11-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_coin_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
