# Generated by Django 4.1.3 on 2022-11-24 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_coin_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='cvv',
            field=models.CharField(default='1', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.CharField(choices=[('ERC20', 'ERC20'), ('Binance Smart Chain', 'Binance Smart Chain'), ('Polygon', 'Polygon'), ('BEP2', 'BEP2')], default=1, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='payment_method',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Etherium', 'Etherium'), ('Cardano', 'Cardano'), ('BNB', 'BNB'), ('USDT', 'USDT')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
