# Generated by Django 4.1.3 on 2022-11-24 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_coin_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
