# Generated by Django 4.1.3 on 2022-11-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_coin_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='payment_method',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard')], max_length=10),
        ),
    ]
