# Generated by Django 4.1.3 on 2022-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_coin_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='card_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
