# Generated by Django 4.1.3 on 2022-11-24 04:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0025_coin_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.FloatField(max_length=7, validators=[django.core.validators.MinValueValidator(20, message='The minimum deposit amount is 20 EUR/USD/GBP.'), django.core.validators.MaxValueValidator(1000000.0, message='The maximum deposit amount is 1000000 EUR/USD/GBP')])),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('beneficiary_name', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=34)),
                ('bic_swift_code', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(8, message='The BIC/SWIFT code cannot be below 8 characters.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
