# Generated by Django 4.1.3 on 2022-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
        migrations.AlterField(
            model_name='coin',
            name='type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Cardano', 'Cardano'), ('BNB', 'BNB'), ('USDT', 'USDT')], max_length=8),
        ),
    ]
