# Generated by Django 4.1.3 on 2022-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_coin_image_alter_coin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(choices=[('BTC', '(24531, 30)'), ('ETH', '(1477, 30)')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Solana', 'Solana'), ('BNB', 'BNB'), ('Polkadot', 'Polkadot'), ('Dash', 'Dash')], max_length=8),
        ),
    ]
