# Generated by Django 4.1.3 on 2022-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_coin_coin_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('19255', '19255'), ('2166', '2166'), ('382', '382'), ('114', '114'), ('14', '14'), ('60', '60')], null=True),
        ),
    ]
