# Generated by Django 4.1.3 on 2022-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_coin_coin_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='fiat_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('21036', '21036'), ('2343', '2343'), ('380', '380'), ('158', '158'), ('9', '9'), ('144', '144')], null=True),
        ),
    ]
