# Generated by Django 4.1.3 on 2022-11-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_coin_fiat_value_alter_coin_coin_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('25021', '25021'), ('2496', '2496'), ('286', '286'), ('92', '92'), ('9', '9'), ('42', '42')], null=True),
        ),
    ]
