# Generated by Django 4.1.3 on 2022-11-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_coin_coin_prices_alter_coin_fiat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('20067', '20067'), ('2461', '2461'), ('400', '400'), ('71', '71'), ('13', '13'), ('147', '147')], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='fiat_value',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
