# Generated by Django 4.1.3 on 2022-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_coin_coin_prices_alter_coin_fiat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '172'), ('Bitcoin', '23622'), ('Ethereum', '1177'), ('BNB', '322'), ('Polkadot', '9'), ('Dash', '146')], null=True),
        ),
    ]
