# Generated by Django 4.1.3 on 2022-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_coin_coin_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '141'), ('Bitcoin', '20693'), ('Ethereum', '2086'), ('BNB', '391'), ('Polkadot', '9'), ('Dash', '69')], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='fiat_value',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Previous Fiat Value'),
        ),
    ]
