# Generated by Django 4.1.3 on 2022-11-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_coin_coin_prices_alter_coin_fiat_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='coin',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '123'), ('Bitcoin', '25393'), ('Ethereum', '1467'), ('BNB', '367'), ('Polkadot', '6'), ('Dash', '111')], null=True),
        ),
    ]
