# Generated by Django 4.1.3 on 2022-11-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_remove_coin_cvv_remove_coin_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '159'), ('Bitcoin', '22803'), ('Ethereum', '2402'), ('BNB', '389'), ('Polkadot', '13'), ('Dash', '63')], null=True),
        ),
    ]
