# Generated by Django 4.1.3 on 2022-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_coin_coin_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '199'), ('Bitcoin', '18514'), ('Ethereum', '1670'), ('BNB', '376'), ('Polkadot', '15'), ('Dash', '110')], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='payment_method',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Fiat Wallet', 'Fiat Wallet')], max_length=11),
        ),
    ]
