# Generated by Django 4.1.3 on 2022-11-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_coin_coin_prices_alter_coin_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_amount',
            new_name='deposited_amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='transfer_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '41'), ('Bitcoin', '21346'), ('Ethereum', '1966'), ('BNB', '324'), ('Polkadot', '6'), ('Dash', '102')], null=True),
        ),
    ]
