# Generated by Django 4.1.3 on 2022-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_rename_deposit_amount_deposit_deposited_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='bic_swift_code',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposited_amount',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transfer_amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '110'), ('Bitcoin', '23863'), ('Ethereum', '1845'), ('BNB', '264'), ('Polkadot', '6'), ('Dash', '59')], null=True),
        ),
    ]
