# Generated by Django 4.1.3 on 2022-11-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_alter_coin_coin_prices_alter_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='iban',
            field=models.CharField(default=1, max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '44'), ('Bitcoin', '24405'), ('Ethereum', '2019'), ('BNB', '336'), ('Polkadot', '6'), ('Dash', '59')], null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(blank=True, max_length=7, null=True),
        ),
    ]
