# Generated by Django 4.1.3 on 2022-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_deposit_iban_alter_coin_coin_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '105'), ('Bitcoin', '16244'), ('Ethereum', '1717'), ('BNB', '267'), ('Polkadot', '6'), ('Dash', '91')], null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(blank=True, default=0, max_length=7, null=True),
        ),
    ]
