# Generated by Django 4.1.3 on 2022-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_coin_coin_prices_two_alter_coin_coin_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', '25'), ('Bitcoin', '16163'), ('Ethereum', '1610'), ('BNB', '298'), ('Polkadot', '14'), ('Dash', '80')], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[('16163', 'Bitcoin'), ('1610', 'Ethereum'), ('298', 'Solana'), ('25', 'BNB'), ('14', 'Polkadot'), ('80', 'Dash')], default=1),
        ),
    ]
