# Generated by Django 4.1.3 on 2022-11-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_coin_coin_prices_alter_coin_coin_prices_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 87), ('Bitcoin', 16430), ('Ethereum', 1571), ('BNB', 259), ('Polkadot', 6), ('Dash', 53), ('Avalanche', 54)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16430, 'Bitcoin'), (1571, 'Ethereum'), (259, 'Solana'), (87, 'BNB'), (6, 'Polkadot'), (53, 'Dash'), (54, 'Avalanche')], default=1),
        ),
        migrations.AlterField(
            model_name='coin',
            name='type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Solana', 'Solana'), ('BNB', 'BNB'), ('Polkadot', 'Polkadot'), ('Dash', 'Dash'), ('Avalanche', 'Avalanche')], max_length=9),
        ),
    ]
