# Generated by Django 4.1.3 on 2022-11-28 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0050_contactus_author_alter_coin_coin_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 76), ('Bitcoin', 16371), ('Ethereum', 1371), ('BNB', 292), ('Polkadot', 5), ('Dash', 46), ('Avalanche', 43)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16371, 'Bitcoin'), (1371, 'Ethereum'), (292, 'Solana'), (76, 'BNB'), (5, 'Polkadot'), (46, 'Dash'), (43, 'Avalanche')], default=1),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
