# Generated by Django 4.1.3 on 2022-11-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_coin_coin_prices_alter_coin_coin_prices_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 41), ('Bitcoin', 16730), ('Ethereum', 1259), ('BNB', 279), ('Polkadot', 13), ('Dash', 57), ('Avalanche', 45)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16730, 'Bitcoin'), (1259, 'Ethereum'), (279, 'Solana'), (41, 'BNB'), (13, 'Polkadot'), (57, 'Dash'), (45, 'Avalanche')], default=1),
        ),
    ]
