# Generated by Django 4.1.3 on 2022-11-29 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_alter_coin_coin_prices_alter_coin_coin_prices_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 86), ('Bitcoin', 16175), ('Ethereum', 1382), ('BNB', 372), ('Polkadot', 15), ('Dash', 93), ('Avalanche', 78)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16175, 'Bitcoin'), (1382, 'Ethereum'), (372, 'Solana'), (86, 'BNB'), (15, 'Polkadot'), (93, 'Dash'), (78, 'Avalanche')], default=1),
        ),
        migrations.AlterField(
            model_name='coin',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='iban',
            field=models.CharField(max_length=34, verbose_name='IBAN'),
        ),
    ]
