# Generated by Django 4.1.3 on 2022-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_alter_coin_coin_prices_alter_coin_coin_prices_two_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpArticle',
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Help Article'},
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 19), ('Bitcoin', 16328), ('Ethereum', 1550), ('BNB', 250), ('Polkadot', 15), ('Dash', 48), ('Avalanche', 40)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16328, 'Bitcoin'), (1550, 'Ethereum'), (250, 'Solana'), (19, 'BNB'), (15, 'Polkadot'), (48, 'Dash'), (40, 'Avalanche')], default=1),
        ),
    ]
