# Generated by Django 4.1.3 on 2022-12-03 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_coin_coin_prices_alter_coin_coin_prices_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 14), ('Bitcoin', 16465), ('Ethereum', 1259), ('BNB', 286), ('Polkadot', 6), ('Dash', 83), ('Avalanche', 98)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16465, 'Bitcoin'), (1259, 'Ethereum'), (286, 'Solana'), (14, 'BNB'), (6, 'Polkadot'), (83, 'Dash'), (98, 'Avalanche')], default=1),
        ),
    ]
