# Generated by Django 4.1.3 on 2022-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_contactus_time_alter_coin_coin_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 34), ('Bitcoin', 16156), ('Ethereum', 1853), ('BNB', 298), ('Polkadot', 6), ('Dash', 89), ('Avalanche', 44)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16156, 'Bitcoin'), (1853, 'Ethereum'), (298, 'Solana'), (34, 'BNB'), (6, 'Polkadot'), (89, 'Dash'), (44, 'Avalanche')], default=1),
        ),
    ]
