# Generated by Django 4.1.3 on 2022-12-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_coin_coin_prices_alter_coin_coin_prices_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Fiat Wallet'},
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 21), ('Bitcoin', 16698), ('Ethereum', 1759), ('BNB', 277), ('Polkadot', 11), ('Dash', 41), ('Avalanche', 84)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16698, 'Bitcoin'), (1759, 'Ethereum'), (277, 'Solana'), (21, 'BNB'), (11, 'Polkadot'), (41, 'Dash'), (84, 'Avalanche')], default=1),
        ),
    ]
