# Generated by Django 4.1.3 on 2022-12-05 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_alter_coin_coin_prices_alter_coin_coin_prices_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='card_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 30), ('Bitcoin', 16529), ('Ethereum', 1749), ('BNB', 259), ('Polkadot', 14), ('Dash', 65), ('Avalanche', 83)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16529, 'Bitcoin'), (1749, 'Ethereum'), (259, 'Solana'), (30, 'BNB'), (14, 'Polkadot'), (65, 'Dash'), (83, 'Avalanche')], default=1),
        ),
        migrations.AlterField(
            model_name='coin',
            name='iban',
            field=models.CharField(max_length=34, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='IBAN'),
        ),
    ]
