# Generated by Django 4.1.3 on 2022-12-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_alter_coin_card_number_alter_coin_coin_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 76), ('Bitcoin', 16429), ('Ethereum', 1674), ('BNB', 250), ('Polkadot', 10), ('Dash', 97), ('Avalanche', 71)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16429, 'Bitcoin'), (1674, 'Ethereum'), (250, 'Solana'), (76, 'BNB'), (10, 'Polkadot'), (97, 'Dash'), (71, 'Avalanche')], default=1),
        ),
    ]
