# Generated by Django 4.1.3 on 2022-12-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_alter_coin_coin_prices_alter_coin_coin_prices_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Coin'},
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 75), ('Bitcoin', 16615), ('Ethereum', 1620), ('BNB', 319), ('Polkadot', 15), ('Dash', 47), ('Avalanche', 56)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16615, 'Bitcoin'), (1620, 'Ethereum'), (319, 'Solana'), (75, 'BNB'), (15, 'Polkadot'), (47, 'Dash'), (56, 'Avalanche')], default=1),
        ),
    ]
