# Generated by Django 3.2.9 on 2022-12-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_coin_options_alter_coin_coin_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 95), ('Bitcoin', 16404), ('Ethereum', 1310), ('BNB', 266), ('Polkadot', 9), ('Dash', 49), ('Avalanche', 53)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16404, 'Bitcoin'), (1310, 'Ethereum'), (266, 'Solana'), (95, 'BNB'), (9, 'Polkadot'), (49, 'Dash'), (53, 'Avalanche')], default=1),
        ),
    ]
