# Generated by Django 3.2.9 on 2022-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_auto_20221207_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 95), ('Bitcoin', 16811), ('Ethereum', 1458), ('BNB', 343), ('Polkadot', 12), ('Dash', 97), ('Avalanche', 66)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16811, 'Bitcoin'), (1458, 'Ethereum'), (343, 'Solana'), (95, 'BNB'), (12, 'Polkadot'), (97, 'Dash'), (66, 'Avalanche')], default=1),
        ),
    ]
