# Generated by Django 3.2.9 on 2022-12-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_auto_20221207_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 80), ('Bitcoin', 16618), ('Ethereum', 1265), ('BNB', 357), ('Polkadot', 5), ('Dash', 69), ('Avalanche', 94)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16618, 'Bitcoin'), (1265, 'Ethereum'), (357, 'Solana'), (80, 'BNB'), (5, 'Polkadot'), (69, 'Dash'), (94, 'Avalanche')], default=1),
        ),
    ]
