# Generated by Django 3.2.9 on 2022-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_auto_20221210_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 18), ('Bitcoin', 16336), ('Ethereum', 1129), ('BNB', 372), ('Polkadot', 9), ('Dash', 98), ('Avalanche', 93)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16336, 'Bitcoin'), (1129, 'Ethereum'), (372, 'Solana'), (18, 'BNB'), (9, 'Polkadot'), (98, 'Dash'), (93, 'Avalanche')], default=1),
        ),
    ]
