# Generated by Django 3.2.9 on 2022-12-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_auto_20221211_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 69), ('Bitcoin', 16688), ('Ethereum', 1198), ('BNB', 356), ('Polkadot', 6), ('Dash', 49), ('Avalanche', 60)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16688, 'Bitcoin'), (1198, 'Ethereum'), (356, 'Solana'), (69, 'BNB'), (6, 'Polkadot'), (49, 'Dash'), (60, 'Avalanche')], default=1),
        ),
    ]
