# Generated by Django 3.2.9 on 2022-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_auto_20221211_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 31), ('Bitcoin', 16641), ('Ethereum', 1636), ('BNB', 251), ('Polkadot', 10), ('Dash', 43), ('Avalanche', 51)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16641, 'Bitcoin'), (1636, 'Ethereum'), (251, 'Solana'), (31, 'BNB'), (10, 'Polkadot'), (43, 'Dash'), (51, 'Avalanche')], default=1),
        ),
    ]
