# Generated by Django 3.2.9 on 2022-12-18 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0072_auto_20221211_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 25), ('Bitcoin', 16398), ('Ethereum', 1455), ('BNB', 366), ('Polkadot', 6), ('Dash', 43), ('Avalanche', 42)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16398, 'Bitcoin'), (1455, 'Ethereum'), (366, 'Solana'), (25, 'BNB'), (6, 'Polkadot'), (43, 'Dash'), (42, 'Avalanche')], default=1),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='author',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
