# Generated by Django 3.2.9 on 2022-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_auto_20221211_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 18), ('Bitcoin', 16435), ('Ethereum', 1540), ('BNB', 301), ('Polkadot', 14), ('Dash', 85), ('Avalanche', 57)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16435, 'Bitcoin'), (1540, 'Ethereum'), (301, 'Solana'), (18, 'BNB'), (14, 'Polkadot'), (85, 'Dash'), (57, 'Avalanche')], default=1),
        ),
    ]
