# Generated by Django 3.2.9 on 2022-12-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_auto_20221218_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_prices',
            field=models.IntegerField(blank=True, choices=[('Solana', 45), ('Bitcoin', 16428), ('Ethereum', 1803), ('BNB', 314), ('Polkadot', 5), ('Dash', 73), ('Avalanche', 74)], null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_prices_two',
            field=models.PositiveSmallIntegerField(choices=[(16428, 'Bitcoin'), (1803, 'Ethereum'), (314, 'Solana'), (45, 'BNB'), (5, 'Polkadot'), (73, 'Dash'), (74, 'Avalanche')], default=1),
        ),
    ]
