# Generated by Django 4.1.3 on 2022-11-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
    ]
